export const authConstants ={
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}

export const userConstants ={
    GET_INIT_DATA_REQUEST:'GET_INIT_DATA_REQUEST',
    GET_INIT_DATA_SUCCESS:'GET_INIT_DATA_SUCCESS',
    GET_INIT_DATA_FAILURE:'GET_INIT_DATA_FAILURE'
}

export const roomConstants ={
    GET_ROOM_DETAILS_REQUEST:'GET_ROOM_DETAILS_REQUEST',
    GET_ROOM_DETAILS_SUCCESS:'GET_ROOM_DETAILS_SUCCESS',
    GET_ROOM_DETAILS_FAILURE:'GET_ROOM_DETAILS_FAILURE',
    REGISTER_ROOM_REQUEST:'REGISTER_ROOM_REQUEST',
    REGISTER_ROOM_SUCCESS:'REGISTER_ROOM_SUCCESS',
    REGISTER_ROOM_FAILURE:'REGISTER_ROOM_FAILURE',
}


export const messagesConstanst ={
    GET_MESSAGES_REQUEST:'GET_MESSAGES_REQUEST',
    GET_MESSAGES_SUCCESS:'GET_MESSAGES_SUCCESS',
    GET_MESSAGES_FAILURE:'GET_MESSAGES_FAILURE',

    SEND_MESSAGES_REQUEST:'SEND_MESSAGES_REQUEST',
    SEND_MESSAGES_SUCCESS:'SEND_MESSAGES_SUCCESS',
    SEND_MESSAGES_FAILURE:'SEND_ROOM_DETAILS_FAILURE',
}