export const authConstants ={
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}

export const roomConstants ={
    GET_ROOM_DETAILS_REQUEST:'GET_ROOM_DETAILS_REQUEST',
    GET_ROOM_DETAILS_SUCCESS:'GET_ROOM_DETAILS_SUCCESS',
    GET_ROOM_DETAILS_FAILURE:'GET_ROOM_DETAILS_FAILURE',
}